springdoc:
  packages-to-scan: com.solace.maas.ep.event.management.agent.scanManager.rest
  api-docs:
    path: /docs/event-management-agent
  swagger-ui:
    path: /event-management-agent/swagger-ui.html
server:
  port: 8180
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:5MB}
      max-file-size: ${MAX_FILE_SIZE:5MB}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:file:./data/cache;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driver-class-name: org.h2.Driver
    password: password
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
camel:
  springboot:
    use-mdc-logging: true
kafka:
  client:
    config:
      reconnections:
        max-backoff:
          unit: milliseconds
          value: 1000
        backoff:
          unit: milliseconds
          value: 50
      connections:
        max-idle:
          unit: milliseconds
          value: 10000
        request-timeout:
          unit: milliseconds
          value: 5000
        timeout:
          unit: milliseconds
          value: 60000
eventPortal:
  solaceManagedAgent: false
  topicPrefix: ${EP_TOPIC_PREFIX:sc/ep/runtime}
  runtimeAgentId: ${EP_RUNTIME_AGENT_ID:1rsyjmbt4wa}
  organizationId: ${EP_ORGANIZATION_ID:localrcorg}
  gateway:
    id: 76bostklti9
    name: evmrcreatedwithlemmy
    messaging:
      standalone: false
      rtoSession: false
      enableHeartbeats: true
      testHeartbeats: true
      connections:
        - name: eventPortalGateway
          authenticationType: ${EP_GATEWAY_AUTH:basicAuthentication}
          msgVpn: ${EP_GATEWAY_MSGVPN:rchakraborty-dev}
          url: ${EP_GATEWAY_URL:tcps://ep-ivmrs-for-devs.messaging.solace.cloud:55443}
          users:
            - clientName: client_1rsyjmbt4wa
              username: ${EP_GATEWAY_USERNAME:localrcorg-v6693yiarsp-1rsyjmbt4wa}
              password: Tc6QiF7!3H-cy}^GpbxQD.xK
              name: messaging1
plugins:
  resources:
    - id: 26dn6j9g9s0
      type: solace
      name: rchakraborty-dev
      connections:
        - name: rchakraborty-dev
          url: https://ep-ivmrs-for-devs.messaging.solace.cloud:943
          properties:
            - name: msgVpn
              value: rchakraborty-dev
            - name: sempPageSize
              value: 100
          authentication:
            - properties:
                - name: type
                  value: basicAuthentication
              protocol: semp
              credentials:
                - properties:
                    - name: username
                      value: rchakraborty-dev
                    - name: password
                      value: rchakraborty-dev
                  source: ENVIRONMENT_VARIABLE
                  operations:
                    - name: ALL
