springdoc:
  packages-to-scan: com.solace.maas.ep.event.management.agent.scanManager.rest
  api-docs:
    path: /docs/event-management-agent
  swagger-ui:
    path: /event-management-agent/swagger-ui.html
server:
  port: 8180
spring:
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    password: password
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:./data/cache;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:5MB}
      max-file-size: ${MAX_FILE_SIZE:5MB}
  main:
    allow-bean-definition-overriding: true
camel:
  springboot:
    use-mdc-logging: true
kafka:
  client:
    config:
      reconnections:
        max-backoff:
          unit: milliseconds
          value: 1000
        backoff:
          unit: milliseconds
          value: 50
      connections:
        max-idle:
          unit: milliseconds
          value: 10000
        request-timeout:
          unit: milliseconds
          value: 5000
        timeout:
          unit: milliseconds
          value: 60000
eventPortal:
  organizationId: ${EP_ORGANIZATION_ID:localrcorg}
  runtimeAgentId: ${EP_RUNTIME_AGENT_ID:3jczd7fk0xv}
  incomingRequestQueueName: "ep_core_ema_requests_fakedcid"
  managed: true
  gateway:
    id: f0ydyzsr1jp
    name: POCCloudManagedEMAEVMR
    messaging:
      standalone: false
      rtoSession: false
      enableHeartbeats: true
      testHeartbeats: true
      connections:
        - name: eventPortalGateway
          authenticationType: ${EP_GATEWAY_AUTH:basicAuthentication}
          msgVpn: ${EP_GATEWAY_MSGVPN:poccloudmanagedemaevmr}
          url: ${EP_GATEWAY_URL:tcps://mr-connection-i41xmmlismp.messaging.solace.cloud:55443}
          users:
            - name: messaging1
              password: UiDFfo0Cbj4}5H5vlp4FEvjI
              username: ${EP_GATEWAY_USERNAME:localrcorg-v6693yiarsp-3jczd7fk0xv}
              clientName: client_3jczd7fk0xv
  topicPrefix: ${EP_TOPIC_PREFIX:sc/ep/runtime}