springdoc:
  packages-to-scan: com.solace.maas.ep.event.management.agent.scanManager.rest
  api-docs:
    path: /docs/event-management-agent
  swagger-ui:
    path: /event-management-agent/swagger-ui.html
server:
  port: 8180
spring:
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:5MB}
      max-file-size: ${MAX_FILE_SIZE:5MB}
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:./data/cache;DB_CLOSE_ON_EXIT=FALSE
    password: password
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
camel:
  springboot:
    use-mdc-logging: true
kafka:
  client:
    config:
      connections:
        max-idle:
          unit: milliseconds
          value: 10000
        request-timeout:
          unit: milliseconds
          value: 5000
        timeout:
          unit: milliseconds
          value: 60000
      reconnections:
        max-backoff:
          unit: milliseconds
          value: 1000
        backoff:
          unit: milliseconds
          value: 50
eventPortal:
  runtimeAgentId: ${EP_RUNTIME_AGENT_ID:av60o82f4ir}
  organizationId: ${EP_ORGANIZATION_ID:localrcorg}
  topicPrefix: ${EP_TOPIC_PREFIX:sc/ep/runtime}
  gateway:
    id: f0ydyzsr1jp
    name: POCCloudManagedEMAEVMR
    messaging:
      standalone: false
      rtoSession: false
      enableHeartbeats: true
      testHeartbeats: true
      connections:
        - name: eventPortalGateway
          authenticationType: ${EP_GATEWAY_AUTH:basicAuthentication}
          msgVpn: ${EP_GATEWAY_MSGVPN:poccloudmanagedemaevmr}
          url: ${EP_GATEWAY_URL:tcps://mr-connection-i41xmmlismp.messaging.solace.cloud:55443}
          users:
            - clientName: client_av60o82f4ir
              name: messaging1
              password: ADttr7Dxf--x9S=wIivwR!qc
              username: ${EP_GATEWAY_USERNAME:localrcorg-v6693yiarsp-av60o82f4ir}
plugins:
  resources:
    - id: 26dn6j9g9s0
      type: solace
      name: rchakraborty-dev
      connections:
        - name: rchakraborty-dev
          url: https://ep-ivmrs-for-devs.messaging.solace.cloud:943
          properties:
            - value: rchakraborty-dev
              name: msgVpn
            - value: 100
              name: sempPageSize
          authentication:
            - properties:
                - value: basicAuthentication
                  name: type
              protocol: semp
              credentials:
                - properties:
                    - name: username
                      value: rchakraborty-dev
                    - name: password
                      value: rchakraborty-dev
                  operations:
                    - name: ALL
                  source: ENVIRONMENT_VARIABLE
