springdoc:
  packages-to-scan: com.solace.maas.ep.runtime.agent.scanManager.rest
  api-docs:
    path: /docs/runtime-agent
  swagger-ui:
    path: runtime-agent/swagger-ui.html
server:
  port: 8180
spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    password: password
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:./data/cache;DB_CLOSE_ON_EXIT=FALSE
camel:
  springboot:
    use-mdc-logging: true
eventPortal:
  runtimeAgentId: ${EP_RUNTIME_AGENT_ID:edrokejxnie}
  topicPrefix: ${EP_TOPIC_PREFIX:sc/ep/runtime}
  gateway:
    id: cfk764cndcy
    name: myEVMR
    messaging:
      standalone: false
      rtoSession: false
      enableHeartbeats: true
      testHeartbeats: true
      connections:
        - name: eventPortalGateway
          authenticationType: ${EP_GATEWAY_AUTH:basicAuthentication}
          msgVpn: ${EP_GATEWAY_MSGVPN:gregs-evmr}
          url: ${EP_GATEWAY_URL:tcps://mr-connection-j4oi66ik2jh.messaging.solace.cloud:55443}
          users:
            - name: messaging1
              password: fbbvL^@jV.r^y7WFFEUjO-5p
              username: ${EP_GATEWAY_USERNAME:greg-le3jp62q2ja-edrokejxnie}
              clientName: client_edrokejxnie
  organizationId: ${EP_ORGANIZATION_ID:greg}
plugins:
  messagingServices:
    - id: 71chd1b4r0i
      type: kafka
      name: kafka scale1
      connections:
        - name: kafkaNoAuthConnection
          url: ${KAFKA_BOOTSTRAP_SERVERS:scale-test1-discovery.mymaas.net:9091}
          authentication:
            - protocol: PLAINTEXT
              credentials:
                - type: noAuth
                  source: ENVIRONMENT_VARIABLE
                  operations:
                    - name: ALL
                  properties: [
                  ]
