springdoc:
  packages-to-scan: com.solace.maas.ep.event.management.agent.scanManager.rest
  api-docs:
    path: /docs/event-management-agent
  swagger-ui:
    path: /event-management-agent/swagger-ui.html
server:
  port: 8180
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:5MB}
      max-file-size: ${MAX_FILE_SIZE:5MB}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./data/cache;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driver-class-name: org.h2.Driver
    password: password
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
camel:
  springboot:
    use-mdc-logging: true
kafka:
  client:
    config:
      reconnections:
        max-backoff:
          unit: milliseconds
          value: 1000
        backoff:
          unit: milliseconds
          value: 50
      connections:
        max-idle:
          unit: milliseconds
          value: 10000
        request-timeout:
          unit: milliseconds
          value: 5000
        timeout:
          unit: milliseconds
          value: 60000
eventPortal:
  runtimeAgentId: ${EP_RUNTIME_AGENT_ID:60ckm35kb8u}
  organizationId: ${EP_ORGANIZATION_ID:localrcorg}
  topicPrefix: ${EP_TOPIC_PREFIX:sc/ep/runtime}
  gateway:
    id: kz7hk9rgv67
    name: rchakraborty-evmr
    messaging:
      standalone: false
      rtoSession: false
      enableHeartbeats: true
      testHeartbeats: true
      connections:
        - name: eventPortalGateway
          authenticationType: ${EP_GATEWAY_AUTH:basicAuthentication}
          msgVpn: ${EP_GATEWAY_MSGVPN:rchakraborty-evmr}
          url: ${EP_GATEWAY_URL:tcps://mr-connection-x1t4p6a5v0v.messaging.solace.cloud:55443}
          users:
            - clientName: client_60ckm35kb8u
              username: ${EP_GATEWAY_USERNAME:localrcorg-fswn2lx2eih-60ckm35kb8u}
              password: QPF-gR-@-F63M7sPmLYYea+h
              name: messaging1
plugins:
  resources:
    - id: vpg6fo60rxk
      type: solace
      name: rchakraborty-evmr
      connections:
        - name: rchakraborty-evmr
          url: https://mr-connection-x1t4p6a5v0v.messaging.solace.cloud:943
          properties:
            - name: msgVpn
              value: rchakraborty-evmr
            - name: sempPageSize
              value: 100
          authentication:
            - properties:
                - name: type
                  value: basicAuthentication
              protocol: ''
              credentials:
                - properties:
                    - name: username
                      value: rchakraborty-evmr-admin
                    - name: password
                      value: "j630m4g06e9e02a558reb9k9l6"
                  source: ENVIRONMENT_VARIABLE
                  operations:
                    - name: ALL
