springdoc:
  packages-to-scan: com.solace.maas.ep.event.management.agent.scanManager.rest
  api-docs:
    path: /docs/event-management-agent
  swagger-ui:
    path: /event-management-agent/swagger-ui.html
server:
  port: 8180
spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:5MB}
      max-file-size: ${MAX_FILE_SIZE:5MB}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./data/cache;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driver-class-name: org.h2.Driver
    password: password
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
camel:
  springboot:
    use-mdc-logging: true
kafka:
  client:
    config:
      reconnections:
        max-backoff:
          unit: milliseconds
          value: 1000
        backoff:
          unit: milliseconds
          value: 50
      connections:
        max-idle:
          unit: milliseconds
          value: 10000
        request-timeout:
          unit: milliseconds
          value: 5000
        timeout:
          unit: milliseconds
          value: 60000

