name: Build
on:
  push:
    branches:
      add_deploy_stage
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Test_Build:
    name: Run Tests and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Setup Build Params
        run: |
          export SKIP_FLAGS_NON_UNIT_TESTS="-Dcheckstyle.skip -Dpmd.skip -Dcpd.skip -Dfindbugs.skip -Dspotbugs.skip"
          export SKIP_FLAGS_UNIT_TESTS="-Dmaven.test.skip=true"
          #echo "SKIP_FLAGS_NON_UNIT_TESTS=$SKIP_FLAGS_NON_UNIT_TESTS" >> $GITHUB_ENV
          echo "SKIP_FLAGS_UNIT_TESTS=$SKIP_FLAGS_UNIT_TESTS" >> $GITHUB_ENV
          echo "SKIP_FLAGS_ALL_TESTS=$SKIP_FLAGS_NON_UNIT_TESTS $SKIP_FLAGS_UNIT_TESTS" >> $GITHUB_ENV
      - run: |
          echo "$SKIP_FLAGS_UNIT_TESTS"
          echo "$SKIP_FLAGS_ALL_TESTS"
#      - name: Static Code Analysis
#        run: mvn -B compile -Pmaas-static-code-analysis --file service/pom.xml
#      - name: Unit Tests
#        run: mvn -B test ${{env.SKIP_FLAGS_NON_UNIT_TESTS}} --file service/pom.xml
#      - name: Generate Artifacts
#        run: |
#          SKIP_TESTS_FLAGS="${{env.SKIP_FLAGS_NON_UNIT_TESTS}} ${{env.SKIP_FLAGS_UNIT_TESTS}}"
#          mvn install $SKIP_TESTS_FLAGS --file service/pom.xml
#      - name: Sonar Scan
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#        run: |
#          SKIP_TESTS_FLAGS="${{env.SKIP_FLAGS_NON_UNIT_TESTS}} ${{env.SKIP_FLAGS_UNIT_TESTS}}"
#          mvn -B $SKIP_TESTS_FLAGS \
#            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=SolaceLabs_runtime-agent \
#            --file service/pom.xml
#      - name: Deploy Artifacts
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          SKIP_TESTS_FLAGS="${{env.SKIP_FLAGS_NON_UNIT_TESTS}} ${{env.SKIP_FLAGS_UNIT_TESTS}}"
#          mvn deploy $SKIP_TESTS_FLAGS -Dmaven.install.skip=true --file service/pom.xml
