name: Build
on:
  push:
    branches:
      - add_whitesource
    paths-ignore:
      - '.gitignore'
#      - '.github/**'
      - '**/*.md'
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Test_Build:
    name: Run Tests and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Set Build Params
        run: |
          export SKIP_FLAGS_NON_UNIT_TESTS="-Dcheckstyle.skip -Dpmd.skip -Dcpd.skip -Dfindbugs.skip -Dspotbugs.skip"
          echo "SKIP_FLAGS_NON_UNIT_TESTS=$SKIP_FLAGS_NON_UNIT_TESTS" >> $GITHUB_ENV
          echo "SKIP_FLAGS_ALL_TESTS=$SKIP_FLAGS_NON_UNIT_TESTS -Dmaven.test.skip=true" >> $GITHUB_ENV
#      - name: Static Code Analysis
#        run: mvn -B compile -Pmaas-static-code-analysis --file service/pom.xml
#      - name: Unit Tests
#        run: mvn -B test $SKIP_FLAGS_NON_UNIT_TESTS --file service/pom.xml
      - name: Generate Artifacts
        run: |
          mvn install $SKIP_FLAGS_ALL_TESTS --file service/pom.xml
#      - name: Sonar Scan
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#        run: |
#          mvn -B $SKIP_FLAGS_ALL_TESTS \
#            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=SolaceLabs_runtime-agent \
#            --file service/pom.xml
      - name: Download latest Mend/Whitesource Agent
        if: ${{ github.ref == 'refs/heads/add_whitesource' }}
        env:
          unified_agent_url: "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar"
          unified_agent_sha_url: "https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar.sha256"
        run: |
          curl -LJO ${{ env.unified_agent_url }}
          sha_from_jar=$(sha256sum  wss-unified-agent.jar | awk '{print $1}')
          curl -LJO ${{ env.unified_agent_sha_url }}
          sha_from_file=$(cat wss-unified-agent.jar.sha256 | awk '{print $1}')
          echo "sha_from_jar: $sha_from_jar"
          echo "sha_from_file: $sha_from_file"
          if [[ "$sha_from_file" == "$sha_from_jar" ]]; then
              echo "Integrity of the wss-unified-agent.jar file verified .."
          else
              echo "Integrity check of wss-unified-agent.jar file failed .."
              exit 1
          fi
      - name: Copy Maven Dependencies
        run: mvn dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=target/lib --file service/pom.xml
      - name: Perform Whitesource Scan
        if: ${{ github.ref == 'refs/heads/add_whitesource' }}
        env:
          WS_APIKEY: ${{ secrets.WHITESOURCE_API_KEY }}
          WS_PROJECTTOKEN: ${{ secrets.WHITESOURCE_PROJECT_TOKEN }}
          TARGET_DIR: "service/application/target/lib"
          WS_EXCLUDES: "local-storage-plugin*.jar,plugin*.jar,kafka-plugin*.jar,confluent-schema-registry-plugin*.jar"
        run: java -jar wss-unified-agent.jar -d  ${{ env.TARGET_DIR }}  -logLevel info

#      - name: Deploy Artifacts
#        if: ${{ github.ref == 'refs/heads/main' }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          mvn deploy $SKIP_FLAGS_ALL_TESTS -Dmaven.install.skip=true --file service/pom.xml
