name: Build
on:
  push:
    branches:
      add_sonarqube_to_build
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Run_Tests_Build_Artifact:
    runs-on: ubuntu-latest
    env:
      SKIP_FLAGS_NON_UNIT_TESTS: "-Dcheckstyle.skip -Dpmd.skip -Dcpd.skip -Dfindbugs.skip -Dspotbugs.skip"
      SKIP_FLAGS_UNIT_TESTS: "-Dmaven.test.skip=true"    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      # - name: Static Code Analysis
      #   run: mvn -B compile -Pmaas-static-code-analysis --file service/pom.xml
      # - name: Unit Tests
      #   run: mvn -B test ${{env.SKIP_FLAGS_NON_UNIT_TESTS}} --file service/pom.xml
      - name: Sonar Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          SKIP_TESTS_FLAGS="${{env.SKIP_FLAGS_NON_UNIT_TESTS}} ${{env.SKIP_FLAGS_UNIT_TESTS}}"
          mvn -B verify $SKIP_TESTS_FLAGS org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=SolaceLabs_runtime-agent --file service/pom.xml
