name: Build
on:
  push:
    branches:
      build_workflow
jobs:
  Run_Tests_Build_Artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
      - name: Static Code Analysis
        run: mvn -B compile -Pmaas-static-code-analysis --file service/pom.xml
      - name: Unit Tests
        run: mvn -B test -Dcheckstyle.skip -Dpmd.skip -Dcpd.skip -Dfindbugs.skip -Dspotbugs.skip --file service/pom.xml
